### ISSUE TITLE
Looks good!

### ISSUE THREAD

**Issue by taktikal17** [anbreezee/instabot#1]
Hey @anbreezee!

You script looks good. 
I need to figure out how to get the followers id ( or name )  of an user.
I tested you script, I can get at least one..
Do you think I can get all the followers list?

I am a little bit confuse when it is in russia!

Have a good one!

**Comment by anbreezee** [comment]
Hi! Before we could use this endpoint:
`https://api.instagram.com/v1/users/{user-id}/followed-by/`

But now I see that Instagram API docs tell us that we should use this:
`https://api.instagram.com/v1/users/**self**/followed-by/`

p.s. If you have any questions, please send me email at anbreezee@gmail.com. This repository will be closed soon, unfortunaly.

FRWL :)
